[project]
name = "EECS-449-group-16"
version = "0.1.0"
description = "Command-line Jac project"
entry-point = "main.jac"
kind = "cli"
jac-version = "==0.37.11"

[dependencies]
libsql = "~=0.1"

[dev-dependencies]
watchdog = ">=3.0.0"

[check]
suppress = ["W1037", "W3030"]
